dist: xenial
language: python

jobs:
  include:
  - stage: test
    env: PYTHON3
    python: 3.6
    install:
     - pip -q install -U flake8
    script:
     - flake8 ./python/
  - stage: test
    env: POSTGRES
    python: 2.7
    addons:
      postgresql: 9.6
      apt:
        packages:
        - postgresql-9.6-postgis-2.4
    
    before_script:
     - echo "\set ON_ERROR_STOP on" > ~/.psqlrc
    script:
     - cd sql; sed -e 's/@DB_USER@/postgres/' db_settings.sh.template > db_settings.sh; POSTGRES_USER=postgres ./create-db.sh
     - psql -U postgres ged4all < common.sql && psql -U postgres ged4all < ged4all.sql && psql -U postgres ged4all < mover-updates.sql
